FROM nginx:alpine

# Copy the built frontend files to the Nginx HTML directory
COPY ../frontend/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]