# Generated by Django 5.2.9 on 2025-12-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.URLField(blank=True, help_text="URL to user's profile photo", null=True),
        ),
    ]
