# Generated by Django 5.2.9 on 2025-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.TextField(blank=True, help_text='Profile photo as data URL or image URL', null=True),
        ),
    ]
