# Generated by Django 5.2.8 on 2025-11-19 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to=settings.AUTH_USER_MODEL)),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endorsed_user', 'skill'], name='core_endors_endorse_6bf74e_idx')],
                'unique_together': {('endorser', 'endorsed_user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='UserFieldRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('academics', 'Academics'), ('sports', 'Sports'), ('music', 'Music'), ('dance', 'Dance'), ('tech', 'Tech'), ('arts', 'Arts')], max_length=20)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['field', 'period', '-score'], name='core_userfi_field_305701_idx')],
                'unique_together': {('user', 'field', 'period')},
            },
        ),
    ]
